FROM quay.io/fedora/fedora-coreos:testing

RUN rpm-ostree install dnf; dnf -y remove moby-engine; dnf clean all

# Substitute YOUR public key below-private key holder for the following public key will have root access
# Alternatively, this section can be removed if configuring users with kickstart or bootc-image-builder
RUN mkdir /usr/etc-system && \
    echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf && \
    echo 'ssh-rsa AAAAB3.....' > /usr/etc-system/root.keys && chmod 0600 /usr/etc-system/root.keys
