FROM quay.io/centos-bootc/centos-bootc:stream9

RUN dnf -y update && \
    dnf -y install podman subscription-manager crun\* chrony && \
    dnf -y clean all && \
    systemctl enable podman.service && \
    printf "\nconfdir /etc/chrony.d\n" >> /etc/chrony.conf

ADD usr usr
ADD etc etc

RUN systemctl enable rhsmcertd.service podman.socket

RUN groupadd -g 501 core; useradd -u 501 -g 501 core
USER core
RUN systemctl --user enable podman.socket
USER root

#Substitute YOUR public key for the below-private key holder for the following public key will have root access
# podman build --build-arg="SSHPUBKEY=$(cat $HOME/.ssh/id_rsa.pub)" ...
ARG SSHPUBKEY
RUN mkdir /usr/etc-system && \
    echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf && \
    echo $SSHPUBKEY > /usr/etc-system/root.keys && chmod 0600 /usr/etc-system/root.keys

# The following steps should be done in the bootc image.
CMD [ "/sbin/init" ]
STOPSIGNAL SIGRTMIN+3
RUN rpm --setcaps shadow-utils
